---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Install check_mk_agent > v1.4
      apt:
        deb: "http://ftp.lihas.de/debian/packages/check-mk-agent_1.6.0-1_all.deb"
      when: ansible_os_family == 'Debian'
    - name: Install check_mk_agent > v1.4
      package:
        name: check-mk-agent
      when: ansible_os_family != 'Debian'

  roles:
    - role: ansible-role-check-mk-agent
      check_mk_agent_over_ssh: false
      check_mk_agent_plugins_requirements: ["smartmontools"]
      check_mk_agent_plugins: ["smart"]
      check_mk_agent_manual_install: true
