---

- name: Testing check_mk collection
  hosts: localhost
  become: no
  gather_facts: no

  vars:

    check_mk_url: "http://localhost:9090/cmk"
    check_mk_automation_user: "automation"
    check_mk_automation_passwd: "automation"

  tasks:

    - name: Add a host
      pescobar.check_mk.host:
        base_url: "{{ check_mk_url }}"
        auth_username: "{{ check_mk_automation_user }}"
        auth_password: "{{ check_mk_automation_passwd }}"
        hostname: test_host_55
        ipaddress: 192.168.10.66
        alias: just_test_alias_55
        folder: test_folder_2
        state: present
      register: check_mk_host_info
      tags: host

    - name: Verify that the host has been created
      assert:
        that:
          - check_mk_host_info.host_info.hostname == 'test_host_55'
          - check_mk_host_info.host_info.attributes.ipaddress == '192.168.10.66'
        success_msg: "Host added"
        fail_msg: "Failed adding a host"
      tags: host

    - name: Add a folder
      pescobar.check_mk.folder:
        base_url: "{{ check_mk_url }}"
        auth_username: "{{ check_mk_automation_user }}"
        auth_password: "{{ check_mk_automation_passwd }}"
        hostname: test_folder_4
        state: present
      register: check_mk_folder_info
      tags: folder

    - name: Verify that the folder has been created
      assert:
        that:
          - check_mk_folder_info.folder_info.folder_name == 'test_folder_4'
          - check_mk_folder_info.folder_info.attributes.meta_data.created_by == 'ansible'
        success_msg: "Folder added"
        fail_msg: "Failed adding a folder"
      tags: folder

    - name: Add a hostgroup
      pescobar.check_mk.hostgroup:
        base_url: "{{ check_mk_url }}"
        auth_username: "{{ check_mk_automation_user }}"
        auth_password: "{{ check_mk_automation_passwd }}"
        hostgroup: hostgroup1
        alias: webservers
        state: present
      register: check_mk_hostgroup_info
      tags: hostgroup

    - name: Verify that the hostgroup has been created
      assert:
        that:
          - check_mk_hostgroup_info.hostgroup_info.hostgroup == 'hostgroup1'
          - check_mk_hostgroup_info.hostgroup_info.alias == 'webservers'
        success_msg: "hostgroup added"
        fail_msg: "Failed adding a hostgroup"
      tags: hostgroup

    - name: Add a servicegroup
      pescobar.check_mk.servicegroup:
        base_url: "{{ check_mk_url }}"
        auth_username: "{{ check_mk_automation_user }}"
        auth_password: "{{ check_mk_automation_passwd }}"
        servicegroup: servicegroup1
        alias: dbs2
        state: present
      register: check_mk_servicegroup_info
      tags: servicegroup

    - name: Verify that the servicegroup has been created
      assert:
        that:
          - check_mk_servicegroup_info.servicegroup_info.servicegroup == 'servicegroup1'
          - check_mk_servicegroup_info.servicegroup_info.alias == 'dbs2'
        success_msg: "servicegroup added"
        fail_msg: "Failed adding a servicegroup"
      tags: servicegroup
