---
galaxy_info:
  author: elnappo <elnappo@nerdpol.io>
  description: Install check_mk agent
  license: MIT
  min_ansible_version: 2.3

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - monitoring

dependencies: []
