name: ci-test

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Boot the docker containers with latest check_mk raw edition
      working-directory: ./devel-utils
      run: |
        docker-compose up -d
        docker exec -ti check-mk-ci bash -c "until [ -f /opt/omd/sites/cmk/var/check_mk/web/automation/automation.secret ]; do sleep 1; done; echo automation > /opt/omd/sites/cmk/var/check_mk/web/automation/automation.secret"

    - name: Install latest ansible and make the collection available
      run: |
        mkdir -p ~/.ansible/collections/ansible_collections/pescobar/
        ln -s ${GITHUB_WORKSPACE} ~/.ansible/collections/ansible_collections/pescobar/check_mk
        pip install ansible

    - name: Execute the CI playbook
      working-directory: ./devel-utils
      run: ansible-playbook playbook-test-ci.yml
